version: "3.8"


volumes:
  postgres_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:

  adminer:
    image: "adminer:4.8.1"
    restart: always
    ports:
      - 8080:8080
    networks:
      - php_advanced

  postgres:
    image: "postgres:14.0"
    restart: always
    environment:
      POSTGRES_PASSWORD: secrettop
    ports:
      - "5432:5432"
    volumes:
      - "postgres_volume:/var/lib/postgresql/data"
    networks:
      - php_advanced

  php:
#    image: "php:8.1-apache"
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - php_advanced


