version: "3.8"

volumes:
  mysql_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  mysql:
    image: "mysql:8"
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    networks:
      - php_advanced

  php:
    #        image: "php:8.1-apache"#
    #        environment:
    #          XDEBUG_MODE: "develop,debug"
    #          XDEBUG_CONFIG: 'client_host=172.17.0.1 log_level=0'
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8081:80"
    networks:
      - php_advanced

